config/routes.rb
Rails.application.routes.draw do
  # Salaries
  resources :salary_booking_templates do
    member do
      get :copy
    end
  end

  resources :salary_templates do
    member do
      get :copy
      get :new_salary_item
    end
    collection do
      get :new_salary_item
    end
  end

  resources :salaries do
    collection do
      get :select_employee
    end

    member do
      get :payslip
    end

    # Line Items
    member do
      get :new_line_item
    end
    collection do
      get :new_line_item
    end
  end

   get 'salary_reports/:action', :controller => :salary_reports
   get 'salary_reports/salary_declaration', :to => 'salary_reports#salary_declaration', :as => :salary_declaration
end

app/models/salary.rb
class Salary < Invoice
  # Association customizing
  belongs_to :employee, :foreign_key => :company_id, :class_name => 'Employee'
  belongs_to :employer, :foreign_key => :customer_id, :class_name => 'Person'

  validates :employee, :employer, :presence => true

  def employer_id=(value)
    self.customer_id = value
  end
  def employer_id
    customer_id
  end

  def employee_id=(value)
    self.company_id = value
  end
  def employee_id
    company_id
  end

  # Emplyoment helpers
  def employment
    employee.employments.valid_at(value_date).last
  end

  def hourly_paid?
    employment.try(:hourly_paid?)
  end

  def track_hours?
    # No tracking if we have no information how payment is done
    return false if hourly_paid?.nil?

    # No tracking if paid by hour
    return false if hourly_paid?

    # No tracking if we have no current information
    return false unless work_days.present?
  end

  def track_leave_days?
    # No tracking if we have no information how payment is done
    return false if hourly_paid?.nil?

    # No tracking if paid by hour
    return false if hourly_paid?

    # No tracking if we have no current information
    return false unless used_leave_days && leave_days_balance

    # Track otherwise
    return true
  end

  # States
  # ======
  STATES = ['booked', 'canceled', 'paid']

  # String
  def to_s(format = :default)
    case format
    when :long
      "%s (%s / %s - %s)" % [title, employee, duration_from ? I18n::localize(duration_from) : '', duration_to ? I18n::localize(duration_to) : '']
    else
      title
    end
  end

  # Helpers
  def previous
    employee.salaries.order("duration_to DESC").where("duration_to < ?", duration_to).first
  end

  # Calculations
  def ahv_amount
    amount_of('AHV')
  end

  def net_amount
    # TODO: hardcoded salary_booking_template
    amount_of('6500')
  end

  def gross_amount
    # TODO: hardcoded salary_booking_template
    amount_of('5000')
  end

  def bvg_amount
    # TODO: hardcoded salary_booking_template
    amount_of('5050')
  end

  # Assignment proxies
  def duration_from=(value)
    write_attribute(:duration_from, value)

    value_as_date = self.duration_from
    # Calculate value and due dates
    date = Date.new(value_as_date.year, value_as_date.month, 1).in(1.month).ago(1.day)
    self.value_date ||= date
    self.due_date   ||= date
  end

  # Get salary template
  #
  # Tries to get a personal salary template, falls back to templates with
  # no assigned persons.
  #
  # If more than one template matches the criteria, it is unspecified which
  # one will be returned.
  def salary_template
    template = SalaryTemplate.where(:person_id => employee.id).last
    template ||= SalaryTemplate.where(:person_id => nil).last
  end

  # Line Items
  def build_line_items
    salary_template.salary_items.each do |salary_item|
      line_item = salary_item.build_line_item

      line_item.date    = self.value_date
      self.line_items << line_item
    end
  end


  # Filter/Search
  # =============
  scope :by_date, lambda {|from, to| where("date(value_date) BETWEEN ? AND ?", from, to) }
  scope :by_employee, lambda {|value| where(:company_id => value)}

  # Accounts
  # ========
  def self.direct_account
    Account.find_by_code("2050")
  end

  def self.available_credit_accounts
    Account.all
  end

  def self.credit_account
    Account.find_by_code('5000')
  end

  def self.available_debit_accounts
    Account.all
  end

  def self.debit_account
    self.direct_account
  end

  # bookyt_projects
  def hours_carry
    WorkDay.create_or_update_upto(employee, duration_to)
    last_day = employee.work_days.where(:date => duration_from.ago(1.day)).last

    return 0 unless last_day

    return last_day.overall_overtime
  end

  def work_days
    WorkDay.create_or_update_upto(employee, duration_to)
    employee.work_days.where(:date => duration_from..duration_to)
  end
end

app/controllers/salaries_controller.rb
class SalariesController < InvoicesController
  defaults :resource_class => Salary

  respond_to :html, :pdf

  # Filter/Search
  # =============
  has_scope :by_date, :using => [:from, :to], :default => proc { |c| c.session[:has_scope] }
  has_scope :by_employee

  # Actions
  # =======
  def select_employee
    # Allow pre-seeding some parameters
    salary_params = {
      :duration_from  => Date.today.beginning_of_month
    }

    # Set default parameters
    salary_params.merge!(params[:salary]) if params[:salary]

    @salary = Salary.new(salary_params)
  end

  def new
    @salary = Salary.new(params[:salary])
    @salary.state = 'booked'

    unless @salary.employee
      # Trigger validation to flag bad values in select form
      @salary.valid?

      render :action => 'select_employee' and return
    end

    # Deduced defaults
    @salary.employer_id = current_tenant.company.id
    month_name          = t('date.month_names')[@salary.duration_from.month]
    @salary.title       = "Lohn #{month_name} #{@salary.duration_from.year} - #{@salary.employee.vcard.full_name}"
    @salary.duration_to = @salary.duration_from.end_of_month

    @salary.leave_days_balance = @salary.previous.try(:leave_days_balance) || 0
    @salary.used_leave_days = 0

    # Prebuild line items
    @salary.build_line_items

    # Prebuild an empty attachment instance
    @salary.attachments.build

    new!
  end

  def payslip
    @salary = Salary.find(params[:id])

    @include_hours_table = @salary.track_hours?
    @include_leave_days_table = @salary.track_leave_days?

    if @include_hours_table
      @hours_carry = @salary.hours_carry

      work_days = @salary.work_days
      @hours_due = work_days.sum(:hours_due)
      @hours_worked = work_days.sum(:hours_worked)
      @hours_saldo = work_days.last.overall_overtime
    end

    show! do |format|
      format.html { redirect_to :action => :show }
    end
  end
end

app/views/salaries/_form.html.haml
= simple_form_for resource do |f|
  = f.input :employee_id, :as => :hidden
  = f.input :employer_id, :as => :hidden
  = f.input :state, :as => :hidden
  .row-fluid
    .span12= f.input :title
  .row-fluid
    .span6= f.input :duration_from, :as => :date_field
    .span6= f.input :duration_to, :as => :date_field
  .row-fluid
    .span6= f.input :used_leave_days, :as => :string, :input_html => {:class => 'span2'}
    .span6= f.input :leave_days_balance, :as => :string, :input_html => {:class => 'span2'}
  .row-fluid
    .span12= f.input :text, :input_html => {:rows => 4}
  .row-fluid
    .span12= f.input :remarks, :input_html => {:rows => 4}

  = render 'line_items/list_form', :f => f, :invoice => resource

  .form-actions
    = f.button :submit

app/views/salaries/_list.html.haml
= render 'salaries/sidebar'

%table.table.table-striped.salaries.collection
  %thead
    %tr
      %th= t_attr :value_date, Invoice
      %th= t_attr :company, Invoice
      %th= t_attr :title, Invoice
      %th= t_attr :due_date, Invoice
      %th.currency= t_attr :gross_amount, Salary
      %th.currency= t_attr :net_amount, Salary
      %th.currency= t_attr :balance, Invoice
      %th.action-links
  %tbody
    = render @salaries

app/views/salaries/_salary.html.haml
%tr[salary]
  %td= salary.value_date
  %td= link_to salary.company, salary.company
  %td= link_to salary.title, salary, {'data-href-container' => 'tr'}
  %td= salary.due_date
  %td.currency= currency_fmt(salary.gross_amount)
  %td.currency= currency_fmt(salary.net_amount)
  %td.currency= currency_fmt(salary.balance(nil, Account.find_by_code('2050')))
  %td.action-links
    = list_link_for(:edit, salary)

app/views/salaries/_salary_certificate.html.haml
%h3= t('salary_certificate')

%table.list
  %tr
    %th= t_attr :ssn, Employee
    %th= t_attr :date_of_birth, Employee
    %th= t_attr :full_name, Employee
    %th= t_attr :duration_from, Employment
    %th= t_attr :duration_to, Employment
    %th.currency AHV-Lohn
    %th.currency ALV-Lohn
    %th.currency ALVZ-Lohn
    %th M/F

  - for employment in @employments
    %tr
      %td= employment.employee.ssn
      %td= employment.employee.date_of_birth
      %td= employment.employee.vcard.full_name
      %td= employment.duration_from || @value_period.first
      %td= employment.duration_to || @value_period.last
      %td.currency= currency_fmt(employment.employee.salaries.where(:value_date => @value_period).sum(&:ahv_amount))
      %td.currency= currency_fmt(employment.employee.salaries.where(:value_date => @value_period).sum(&:ahv_amount))
      %td.currency= currency_fmt(0)
      %td= employment.employee.sex_to_s

  %tr
    %th= t('bookyt.total')

- content_for :sidebar do
  .sub-tabs
    %h3 Filter
    %ul
      - years = current_tenant.incorporated_on.year..Date.today.year
      - for year in years
        %li= link_to year, url_for(params.merge({:by_value_period => {:from => Date.new(year, 1, 1).to_s(:db), :to => Date.new(year, 12, 31).to_s(:db)}}))

app/views/salaries/_sidebar.html.haml
= render 'filters/salary_state'

app/views/salaries/index.html.haml
.contextual
  = icon_link_to :new, {:action => :select_employee}

= boot_page_title

= paginated_section collection do
  - if collection.any?
    = render "list"

= render 'filters/by_calendar_year'
= render 'filters/by_employee'

app/views/salaries/select_employee.html.haml
= boot_page_title

= simple_form_for resource, :url => new_salary_path, :method => :get do |f|
  .row-fluid
    .span12
      =f.association :employee, :as => :combobox
  .row-fluid
    .span12
      = f.input :duration_from, :as => :date_field

  .form-actions
    = f.button :submit

app/views/salaries/show.html.haml
.contextual
  = icon_link_to :payslip, {:action => :payslip, :format => :pdf}, :icon => :print
  = contextual_links_for

=boot_page_title

- bookings = Booking.by_reference(resource)
- accounts = bookings.accounts
.tabbable
  %ul.nav.nav-tabs
    %li.active= link_to t_model, '#tab-main', {:data => {:toggle => 'tab'}}
    - accounts.each do |account|
      %li= link_to account.to_s, "#tab-account-#{account.id}", {:data => {:toggle => 'tab'}}

.tab-content
  #tab-main.tab-pane.active= render "form"
  - accounts.each do |account|
    %div.tab-pane{:id => "tab-account-#{account.id}"}= render 'direct_bookings/show', :reference => resource, :direct_account => account