config/routes.rb
Rails.application.routes.draw do
  # Salaries
  resources :salary_booking_templates do
    member do
      get :copy
    end
  end

  resources :salary_templates do
    member do
      get :copy
      get :new_salary_item
    end
    collection do
      get :new_salary_item
    end
  end

  resources :salaries do
    collection do
      get :select_employee
    end

    member do
      get :payslip
    end

    # Line Items
    member do
      get :new_line_item
    end
    collection do
      get :new_line_item
    end
  end

   get 'salary_reports/:action', :controller => :salary_reports
   get 'salary_reports/salary_declaration', :to => 'salary_reports#salary_declaration', :as => :salary_declaration
end

app/controllers/salary_reports_controller.rb
class SalaryReportsController < ApplicationController
  respond_to :html, :pdf

  # Filter/Search
  # =============
  before_filter do
    @by_date = Date.parse(params[:by_date][:from] || Date.today.beginning_of_year)..Date.parse(params[:by_date][:to] || Date.today.end_of_year) if params[:by_date]
    @by_date ||= Date.today.beginning_of_year..Date.today.end_of_year

    if employee_id = params[:by_employee]
      @employee = Employee.find(employee_id)
    end
  end

  def yearly_ahv_statement
    @employments = Employment.valid_during(@by_date).all
  end

  def salary_declaration
    @salaries = @employee.salaries.where(:value_date => @by_date)
    @line_items = @salaries.collect{|salary| salary.line_items}.flatten

    # TODO: better sorting
    @salary_declaration_codes = SalaryBookingTemplate.pluck(:salary_declaration_code).uniq.select{|code| code.present?}
  end

  def statistics
    @year = @by_date.first.year

    @salary_booking_templates = SalaryBookingTemplate.all
  end
end

app/helpers/salary_report_helper.rb
module SalaryReportHelper
  def duration_from(employment, value_period)
    return value_period.first if employment.duration_from.nil?

    [value_period.first, employment.duration_from].max
  end

  def duration_to(employment, value_period)
    return value_period.last if employment.duration_to.nil?

    [value_period.last, employment.duration_to].min
  end
end

app/views/salary_reports/salary_declaration.html.haml
= boot_page_title

%table.table.table-striped
  - @salary_declaration_codes.each do |code|
    %tr
      %th= code
      %td.currency= @line_items.select{|li| li.booking_template.salary_declaration_code == code}.sum(&:total_amount).floor

= render 'filters/by_calendar_year'
= render 'filters/by_employee'

app/views/salary_reports/statistics.html.haml
= contextual_links

- who = @employee ? @employee : current_tenant
- title = [ t_title, @year.to_s, who.to_s].join(' - ')
= boot_page_title title

%table.table.table-striped.collection
  %thead
    %tr
      %th= t_attr :code, SalaryBookingTemplate
      %th= t_attr :title, SalaryBookingTemplate
      - (1..12).each do |month|
        %th.currency= '%02i/%i' % [month, @year]
      %th.right= t_attr :amount, SalaryBookingTemplate
  %tbody
    - @salary_booking_templates.each do |template|
      - line_items = template.line_items.where(:date => @by_date)
      - line_items = line_items.includes(:invoice).where(invoices: {company_id: @employee.id}) if @employee
      - total_amount = line_items.sum(&:accounted_amount)
      - next if total_amount == 0
      %tr
        %td= template.code
        %td= template.title
        - (1..12).each do |month|
          - duration_from = Date.new(@year, month, 1)
          - duration_to = duration_from.end_of_month
          - duration = duration_from..duration_to
          - amount = line_items.where(:date => duration).sum(&:accounted_amount)
          %td.currency= currency_fmt(amount)
        %td.currency= currency_fmt(total_amount)

= render 'filters/by_calendar_year'
= render 'filters/by_employee'

app/views/salary_reports/yearly_ahv_statement.html.haml
- title = [ t_title, @by_date.last.year ].presence.compact.join(' - ')
= boot_page_title title

%table.table.table-striped.collection
  %thead
    %tr
      %th= t_attr :ssn, Employee
      %th= t_attr :date_of_birth, Employee
      %th= t_attr :full_name, Employee
      %th= t_attr :duration_from, Employment
      %th= t_attr :duration_to, Employment
      %th.currency AHV-Lohn
      %th.currency ALV-Lohn
      %th.currency ALVZ-Lohn
      %th M/F
      %th.action-links
  %tbody
    - ahv_total = 0
    - for employment in @employments
      - ahv_amount = employment.employee.salaries.where(:value_date => @by_date).sum(&:ahv_amount)
      - ahv_total += ahv_amount
      %tr
        %td= employment.employee.ssn
        %td= employment.employee.date_of_birth
        %td= employment.employee.vcard.full_name
        %td= duration_from(employment, @by_date)
        %td= duration_to(employment, @by_date)
        %td.currency= currency_fmt(ahv_amount)
        %td.currency= currency_fmt(ahv_amount)
        %td.currency= currency_fmt(0)
        %td= employment.employee.sex_to_s
        %td.action-links= link_to t_action(:salary_declaration), salary_declaration_path(:by_employee => employment.employee, :by_date => params[:by_date])

  %tfoot
    %tr
      %th= t('bookyt.total')
      %th{:colspan => 4}
      %th.currency= currency_fmt(ahv_total)
      %th.currency= currency_fmt(ahv_total)
      %th.currency= currency_fmt(0)
      %th
      %th.action-links

= render 'filters/by_calendar_year'